services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: mbolger
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: book_scraper
    volumes:
      - book_scraper_postgres_data_v2:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  scraper:
    build: 
      context: .
      target: dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://mbolger:password123@db:5432/book_scraper
    depends_on:
      - db
    tty: true 
    privileged: true
    ports:
      - "5678:5678"
    command: sleep infinity

volumes:
  book_scraper_postgres_data_v2:
    # external: true