services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: mbolger
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: book_scraper
    volumes:
      - book_scraper_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  scraper:
    build: 
      context: .
      target: dev_container
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://mbolger:password123@db:5432/book_scraper
    depends_on:
      - db
    # Keeps the container running for you to attach via VS Code
    tty: true 
    # Required for Docker-in-Docker features to initialize
    privileged: true
    command: sleep infinity

  floci:
    container_name: floci_emulator
    image: floci/floci:latest  # Floci is compatible with LocalStack images
    ports:
      - "4566:4566"            # LocalStack/Floci Gateway
      - "4510-4559:4510-4559"  # External services port range for launching lambda functions
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Allow floci to launch docker containers with the lambda functions 

volumes:
  book_scraper_postgres_data:
    external: true
    # driver: local