[project]
name = "book_arbitrage"
version = "0.1.0"
description = "Scrapes book sales data to identify arbitrage opportunities"
readme = "README.md"
requires-python = ">=3.11"

dependencies = ["database", "scraper", "labeler"]


[project.optional-dependencies]
dev = [
    "pytest>=9.0.3",
]

[tool.uv.sources]
database = { workspace = true }
scraper = { workspace = true }
labeler = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]