"""add batch_id to labels

Revision ID: c892b319910f
Revises: 
Create Date: 2026-08-05 14:03:59.041191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c892b319910f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'magazine',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('books', 'set',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('labels', sa.Column('batch_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labels', 'batch_id')
    op.alter_column('books', 'set',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('books', 'magazine',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
